[package]
name = "marcher"
version = "0.1.0"
authors = ["Liam Pribis <jackpribis@gmail.com>"]
edition = "2018"

[dependencies]
minifb = "0.16"
num-complex = "0.2.4"
cgmath = "0.17.0"
rayon = "1.3.0"
clap = "2.33.1"

[dependencies.image]
version = "0.23.4"
default-features = false
features = ["png"]